OnesEcommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('ecommerce.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include("django.contrib.auth.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.urls import path
from . import views

app_name='ecommerce'

urlpatterns=[
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('',views.Home.as_view(),name='home'),
    path('home/',views.Home.as_view(),name='home'),
    path('products/',views.ProductsView.as_view(),name='products'),
    path('addproduct/',views.AddProductView.as_view(),name='addproduct'),
    path('register/',views.register,name='register'),
    path('logout/',view=views.userlogout,name='logout')
]

ecommerce/models.py
from enum import auto
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields.reverse_related import ManyToOneRel

# Create your models here.
class UserAddress(models.Model):
    street_name = models.CharField(max_length=50,null=False)
    state = models.CharField(max_length=50,null=False)
    city = models.CharField(max_length=50,null=False)
    zipcode = models.IntegerField(null=False)
    def __str__(self):
        return self.street_name

class User(models.Model):
    username = models.CharField(max_length=50,unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    date_registered = models.DateField(auto_now=True)
    user_address = models.ForeignKey(UserAddress,on_delete=CASCADE)

    def __str__(self):
        return self.username

class ProductBrand(models.Model):
    product_brand_name = models.CharField(max_length=50)
    def __str__(self):
        return self.product_brand_name


class ProductCategory(models.Model):
    product_category_name = models.CharField(max_length=50)

    def __str__(self):
        return self.product_category_name

class Product(models.Model):
    product_name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    product_image = models.ImageField(upload_to='images/')
    product_price = models.DecimalField(max_digits=7,null=False,decimal_places=2)
    date_posted=models.DateField(auto_now=True)
    available = models.BooleanField(default=True)
    product_brand = models.ForeignKey(ProductBrand,on_delete=CASCADE)
    product_category=models.ForeignKey(ProductCategory,on_delete=CASCADE,default=1)


    def __str__(self):
        return self.product_name

class ProductReview(models.Model):
    product_review = models.CharField(max_length=500)
    #product = models.ForeignKey(Product,on_delete=CASCADE,default=1)
    def __str__(self):
        return self.product_review

ecommerce/forms.py
from django import forms
from django.db.migrations.operations import fields
from django.forms import widgets
from .models import Product, User

class SignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields=[
            'username',
            'first_name',
            'last_name',
            'user_address',
            'email'
            ]
        widgets={
            'username':forms.TextInput(attrs={'class':'form-control','placeholder':'username'}),
            'first_name':forms.TextInput(attrs={'class':'form-control','placeholder':'first name'}),
            'last_name':forms.TextInput(attrs={'class':'form-control','placeholder':'last name'}),
            'user_address':forms.Select(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control','placeholder':'email'}),
            
        }



class AddProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields=[
           'product_name',
           'description',
           'product_image',
           'product_price',
           'product_category',
           'product_brand',
           'available',
        ]
        widgets={
            'product_name':forms.TextInput(attrs={'class':'form-control','placeholder':'product name'}),
            'description':forms.Textarea(attrs={'class':'form-control','placeholder':'product description'}),
           'product_category':forms.Select(attrs={'class':'form-control'}),
           'product_brand':forms.Select(attrs={'class':'form-control'}),
        }

ecommerce/views.py
from django.shortcuts import render,redirect
from django.views import generic
from .models import User,Product
from .forms import SignUpForm,AddProduct
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login,logout
# Create your views here.
def userlogout(request):
    logout(request)
def register(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        print("in register function")
        if form.is_valid:
            
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            form.save()
            user = authenticate(request,username=username,password=password)
            login(request,user=user)
            return redirect('home')
    else:
            form = UserCreationForm()
    context = {'form':form}
    return render(request=request,template_name="registration/register.html",context=context)

class SignUp(generic.CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'ecommerce/signup.html'
    success_url='../home'

    def get_initial(self):
        initial = super().get_initial()
        #initial['username'] = 'enter your name'
        return initial


class Home(generic.TemplateView):
    template_name = 'ecommerce/home.html'


class ProductsView(generic.TemplateView):
    model= Product
    template_name = 'ecommerce/products.html'
    #getting model data 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products']= Product.objects.all()

        return context
class AddProductView(generic.CreateView):
    model = Product
    template_name='ecommerce/addproduct.html'
    form_class = AddProduct
    success_url='../products'

ecommerce/templates/ecommerce/addproduct.html
{% extends 'ecommerce/home.html' %}

{% block content%}
<div class="container-fluid " style="margin-top: 60px;">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-sm-8 text-center">
            <div class="addformdiv">
            <form  class="addform" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" class="btn btn-primary" value="submit">
            </form>
        </div>
        </div>
        <div class="col-2"></div>

    </div>
</div>

{% endblock%}

ecommerce/templates/ecommerce/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'ecommerce/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'ecommerce/main.css' %}">
    <script src="{% static 'ecommerce/js/bootstrap.min.js' %}">
    </script>

</head>
<body class="bg-white">
    <div class="container-fluid">
        <div class="row ">
            <nav class="navbar navbar-expand-lg navbar-light bg-primary bar shadow fixed-top">
            
                <div class="navbar-brand">
                    <h4 class="text-white">ONES E-COMMERCE</h4>
                </div>
                <button class="navbar-toggler" data-bs-toggle="collapse" type="button" data-bs-target="#navbarcontent" >
                    <span class="navbar-toggler-icon">
                    </span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarcontent" >
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{% url 'ecommerce:home' %}" class="nav-link text-white">
                                HOME
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'ecommerce:products' %}" class="nav-link text-white">
                                PRODUCTS
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'ecommerce:addproduct' %}" class="nav-link text-white">
                                ADD PRODUCT
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="" class="nav-link text-white">
                                ABOUT US
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="" class="nav-link text-white dropdown-toggle" data-bs-toggle="dropdown" data-bs-target="#dropdownitem" >
                                SERVICE
                            </a>
                            <ul class="dropdown-menu" id="dropdownitem"> 
                                <li>
                                    <a href="" class="dropdown-item">web development</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a href="" class="dropdown-item"> App development</a>
                                </li>
                                <li>
                                    <a href="" class="dropdown-item">digital makerting </a>
                                </li>
                                <li>
                                    <a href="" class="dropdown-item">graphic design</a>
                                </li>
    
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="" class="nav-link text-white"> FAQ</a>
                        </li>
                        <li class="nav-item">
                            <a href="" class="nav-link text-white">
                                PORTFOLIO
                            </a>
                        </li>
                        <li class="nav-item">
                            contact
                            <button class="rounded-pill d-lg-inline border-primary d-md-none" style="border-radius: 20px;">+254710383551</button>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="" class="nav-link text-white dropdown-toggle" data-bs-toggle="dropdown" data-bs-target="#dropdownitem" >
                                ACCOUNT
                            </a>
                            <ul class="dropdown-menu" id="dropdownitem"> 
                                
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                {% if user.is_authenticated %}
                                    <li>
                                        <a href="{% url 'logout' %}" class="dropdown-item">logout</a>
                                    </li>
                                {% else %}
                                    <li>
                                        <a href="{% url 'login' %}" class="dropdown-item">login</a>
                                    </li>
                                {% endif %}
                                <li>
                                    <a href="" class="dropdown-item">my profile</a>
                                </li>
                                <li>
                                    <a href="" class="dropdown-item">register</a>
                                </li>
    
                            </ul>
                        </li>
                        
                    </ul>
                </div>
        </nav>
        </div>
    </div>


    {% block content %}
        {% if user.is_authenticated %}
            <div class="container-fluid info">
                <div>
                    <div class="row">
                        <div class=" text-center text-blue col-12">
                            <h5 class="fw-bold">welcome to ones e-commerce,make your purchase</h5>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 offset-3 ">
                            <h4 class="text-center">ONES E-COMMERCE</h4>
                            <p class="text-center text-danger">
                                {{user.username}}
                                welcome to ones e-commerce
                            </p>
                            <a href="{% url 'ecommerce:products'%}"><button class="rounded-pill">MAKE YOUR FIRST PURCHASE</button></a>
                        </div>
            
                    </div>
            </div>
        </div>
        {% else %}
            <p>please login <a href="{% url 'login' %}" style="margin-top: 200px;"> click here to login</a></p>
        {% endif %}
   
    {% endblock %}
</body>
</html>

ecommerce/templates/ecommerce/products.html
{% extends 'ecommerce/home.html' %}

{% block content %}

<div class="container" style="margin-top: 60px;">
    <div class="row ">
        {% if products %}
            {% for product in products %}
                <div class="col-sm-12 col-md-6 col-lg-4 mb-5">
                    <div class="card text-center bg-light h-100">
                        <img class="h-70"  src="{{ product.product_image.url }}" alt="{{product.product_name}}">
                        <div class="card-body h-30">
                            <div class="card-title">
                               {{ product.product_name }}
                            </div>
                            <div class="card-subtitle ">
                                <p>price:{{ product.product_price }}</p>
                                <div class=" card-text">
                                    <p>description:{{product.description}}</p>
                                </div>
                            </div>
                        
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else%}
                <p class="text-red">no products</p>
        {% endif %}
    </div>

</div>



{% endblock %}

ecommerce/templates/ecommerce/signup.html
{% extends 'ecommerce/home.html' %}


{% block content %}
<div class="px" style="margin-top: 60px;">
    <div class="container px-40">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8 text-center justify-content-center">
                <form action="" method="post" class="form-group ">
                    {% csrf_token %}
        
                    <fieldset>
                        <legend>sign up</legend>
                        {{ form.as_p }}
                        <input class="btn btn-primary" type="submit" value="submit">
                    </fieldset>
            
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}